apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-server-test
  template:
    metadata:
      labels:
        app: json-server-test
    spec:
      containers:
        - name: json-server-test
          image: regsitry14032025.azurecr.io/json-server:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: json-server-service
spec:
  type: LoadBalancer
  selector:
    app: json-server
  ports:
    - protocol: TCP
      port: 80        # Expose the service on port 80
      targetPort: 3000 # Forward traffic to container port 3000
