apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: json-server
  namespace: default
spec:
  releaseName: json-server
  interval: 5m
  chart:
    spec:
      chart: json-server
      version: 0.1.5
      sourceRef:
        kind: HelmRepository
        name: helm
  values:
    replicaCount: 1
    image:
      repository: regsitry14032025.azurecr.io/json-server
      tag: 0.1.5
    service:
      type: LoadBalancer
      port: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      cpuUtilization: 50
