apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm
  namespace: default
spec:
  interval: 10m
  url: oci://regsitry14032025.azurecr.io/helm
  type: oci
  secretRef:
    name: flux-azure-registry
